AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-example-s3

  Sample SAM Template for sam-example-s3

Parameters:
  LambdaRoleArn:
    Type: String
  ReadBucket:
    Type: String
  OutputBucket:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    # 環境変数の設定
    Environment:
      Variables:
        OutputBucket: !Ref OutputBucket

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      # ロールの設定
      Role: !Ref LambdaRoleArn
      # レイヤーの参照
      Layers:
        - !Ref MyLayerPyminizip
  ## パーミッションの追加
  S3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref HelloWorldFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub arn:aws:s3:::${ReadBucket}
  ## レイヤーの作成
  MyLayerPyminizip:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'mylayer-pyminizip/'
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

Outputs:
  MyFunctionArn:
    Value: !GetAtt HelloWorldFunction.Arn
